# Base configs
baseurl: "https://somshot.github.io/photos"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Praveen Chaturvedi"
subtitle: "See the world through my eyes!"
author: "Praveen Chaturvedi"
bio: "I love taking pictures"
publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
  
